nats_streaming:
  servers:
    - nats://localhost:4222
  cluster_id: test-cluster
  client_id: client_id
  token: ''

nats_jet_stream:
  servers:
    - nats://localhost:4222
  token: ''

testers:
  streaming_performance_tester:
    channel: test_streaming_performance
    times: 100
    message_size: 1

  jetstream_performance_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_size: 1

  jetstream_purge_stream_tester:
    stream: test_jetstream_purge_stream
    subject: test_jetstream_purge_stream
    counts:
      - 100
      - 1000
    message_size: 1

  jetstream_memory_storage_tester:
    stream: test_jetstream_memory_storage
    subject: test_jetstream_memory_storage
    times: 100
    message_size: 10

