nats_streaming:
  servers:
    - nats://localhost:4222
  cluster_id: test-cluster
  client_id: client_id
  token: ''

nats_jet_stream:
  servers:
    - nats://localhost:4222
  token: ''

testers:
  streaming_performance_test:
    channel: ray.fuck
    times: 1000
  jetstream_performance_test:
    stream: ray
    subject: ray.fuck
    times: 1000
  jetstream_purge_stream_test:
    stream: ray
    subject: ray.fuck
    counts:
      - 100
      - 1000
      - 10000
      - 100000

