nats_streaming:
  servers:
    - nats://localhost:4222
  token: dev_sbk_rd
  cluster_id: cluster_id
  client_id: client_id

nats_jet_stream:
  servers:
    - nats://localhost:4222
  token: token

testers:
  jetstream_performance_test:
    stream: ray
    subject: ray.fuck
    times: 10000
  streaming_performance_test:
    channel: ray.fuck
    times: 10000
