nats_streaming:
  servers:
    - nats://localhost:4222
  cluster_id: test-cluster
  client_id: client_id
  token: ''

nats_jet_stream:
  servers:
    - nats://localhost:4222
  token: ''

enabled_testers:
  # 發布效能測試
  - jetstream_publish_tester
  - jetstream_async_publish_tester
  - streaming_publish_tester
  - nats_publish_tester

  # 訂閱效能測試
  - jetstream_subscribe_tester
  - jetstream_chan_subscribe_tester
  - jetstream_pull_subscribe_tester
  - streaming_subscribe_tester

  # 延遲測試
  - jetstream_latency_tester
  - streaming_latency_tester

  # 清除效能測試
  - jetstream_purge_stream_tester

  # FileStorage 和 MemoryStorage 效能比較
  - jetstream_memory_storage_tester

testers:
  # 發布效能測試
  jetstream_publish_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_sizes:
      - 1
      - 80000
  jetstream_async_publish_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_sizes:
      - 1
      - 80000
  streaming_publish_tester:
    channel: streaming_publish_tester
    times: 100
    message_sizes:
      - 1
      - 80000
  nats_publish_tester:
    subject: nats_publish_tester
    times: 100
    message_sizes:
      - 1
      - 80000

  # 訂閱效能測試
  jetstream_subscribe_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_sizes:
      - 1
      - 80000

  jetstream_chan_subscribe_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_sizes:
      - 1
      - 80000

  jetstream_pull_subscribe_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    fetch_counts:
      - 1
      - 10
      - 100
    message_sizes:
      - 1
      - 80000

  streaming_subscribe_tester:
    channel: streaming_subscribe_tester
    times: 100
    message_sizes:
      - 1
      - 80000

  # 延遲測試
  jetstream_latency_tester:
    stream: ray
    subject: ray.fuck
    times: 1000

  streaming_latency_tester:
    channel: streaming_subscribe_tester
    times: 1000

  # 清除效能測試
  jetstream_purge_stream_tester:
    stream: test_jetstream_purge_stream
    subject: test_jetstream_purge_stream
    counts:
      - 1
      - 100
    message_sizes:
      - 1
      - 100

  # FileStorage 和 MemoryStorage 效能比較
  jetstream_memory_storage_tester:
    stream: test_jetstream_memory_storage
    subject: test_jetstream_memory_storage
    times: 100
    message_sizes:
      - 1
      - 100
