nats_streaming:
  servers:
    - nats://localhost:4222
  cluster_id: test-cluster
  client_id: client_id
  token: ''

nats_jet_stream:
  servers:
    - nats://localhost:4222
  token: ''

testers:
  # Streaming 的發布和接收效能測試
  streaming_publish_tester:
    channel: test_streaming_performance
    times: 100
    message_size: 1

  streaming_subscribe_tester:
    channel: test_streaming_performance
    times: 100
    message_size: 1

  # JetStream 的發布和接收效能測試
  jetstream_publish_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_size: 8

  jetstream_subscribe_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_size: 8

  jetstream_chan_subscribe_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    message_size: 8

  jetstream_pull_subscribe_tester:
    stream: ray
    subject: ray.fuck
    times: 100
    fetch_counts:
      - 1
      - 10
      - 100
    message_size: 8

  # JetStream 測試效能測試
  jetstream_purge_stream_tester:
    stream: test_jetstream_purge_stream
    subject: test_jetstream_purge_stream
    counts:
      - 100
      - 1000
    message_size: 1

  # JetStream FileStoarge 和 MemoryStorage 效能比較
  jetstream_memory_storage_tester:
    stream: test_jetstream_memory_storage
    subject: test_jetstream_memory_storage
    times: 100
    message_size: 10
