nats_streaming:
  servers:
    - nats://localhost:4222
  cluster_id: test-cluster
  client_id: client_id
  token: ''

nats_jet_stream:
  servers:
    - nats://localhost:4222
  token: ''

testers:
  jetstream_performance_test:
    stream: ray
    subject: ray.fuck
    times: 1000
  streaming_performance_test:
    channel: ray.fuck
    times: 1000
